#!/usr/bin/env bash

# Update the package index and install nginx
sudo apt-get update
sudo apt-get install nginx -y

# configure the server to port 80
sudo ufw allow 'Nginx HTTP'
# Create a file with the "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx
service nginx start

