#!/usr/bin/env bash
# it Configures an Nginx server so that /redirect_me redirects to another page.
# redirection will be configured as a "301 Moved Permanently"

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir -p /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Hello World!" | sudo tee /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }
}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
