#!/usr/bin/env bash
# it alwasyIndefinitely writes "I am alive" to the file /tmp/my_process.
# it Pauses two seconds in between each message.

while true
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
