#!/usr/bin/env bash
#Displays the time for 12 hours and 59 minutes.
#isplays hours from 0 to 12
#Displays minutes from 1 to 59

hours=0

while [ $hours -le 12 ]
do
  echo "Hour: $hours"
  minute=1
  while [ $minute -le 59 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( hours++ ))
done
